name: ci/cd

on:
  workflow_dispatch:
  push:
    branches: [ main, 'release/*' ]
  pull_request:
    branches: [ main, 'release/*' ]
  # Build once a month, just to be sure things are still working
  schedule:
    - cron: "20 4 14 * *"

jobs:

  core-builds:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: ['24.3', '25.3', '26.0']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.22'
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gnuplot
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    # - name: Dialyzer
    #   run: rebar3 dialyzer
    - name: Proper Tests
      run: rebar3 as test do compile, proper --regressions
    # - name: Run Tests
    #   run: rebar3 ct -c
    - name: Run Unit Tests
      run: rebar3 as test lfe ltest -tall
    # - name: Test Coverage
    #   run: rebar3 as test do proper -c, cover -v --min_coverage=0

  older-builds:
    name: Old Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        otp_version: ['21.3', '22.3', '23.3']

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.15'
    - name: Install Deps
      run: sudo apt-get update && sudo apt-get install -y gnuplot
    - name: Compile
      run: rebar3 compile
    - name: Xref Checks
      run: rebar3 xref
    # - name: Dialyzer
    #   run: rebar3 dialyzer
    - name: Compile Tests
      run: rebar3 as test compile
    - name: Proper Tests
      run: rebar3 as test proper --regressions
    # - name: Run Tests
    #   run: rebar3 ct -c
    - name: Run Unit Tests
      run: rebar3 as test lfe ltest -tall
    # - name: Test Coverage
    #   run: rebar3 as test do proper -c, cover -v --min_coverage=0

  examples:
    name: Examples w/Erlang ${{ matrix.otp_version }}
    runs-on: ubuntu-latest
    needs: [core-builds,older-builds]

    container: erlang:${{ matrix.otp_version }}
    
    strategy:
      matrix:
        otp_version: ['24.3', '25.3', '26.0']

    steps:
    - uses: actions/checkout@v2
    - name: Install Deps
      run: apt-get update && apt-get install -y gnuplot sudo
    - name: Setup System User
      run: useradd -m examplesuser && chown -R examplesuser:examplesuser .
    - name: Compile
      run: |
        sudo -u examplesuser rebar3 compile
        sudo -u examplesuser rebar3 as examples compile
    - name: List Examples
      run: |
        sudo -u examplesuser rebar3 as examples list
    - name: Which gnuplot
      run: which gnuplot
    - name: gnuplot Version
      run: gnuplot --version
    - name: Run the Examples
      run: |
        sudo -u examplesuser rebar3 as examples lfe run -- all true
        sudo -u examplesuser rebar3 as examples lfe run -- fourier-approx true
    - name: List Generated Images
      run: ls -l priv/output/*.jpg
    - name: Show Expected md5sums
      run: cat examples/output.md5sum
    - name: Make md5sum
      run: make md5sum > priv/output/examples.md5sum
    - name: Show Generated md5sums
      run: cat priv/output/examples.md5sum
    - name: Check md5sums
      run: diff -EBbiw --suppress-common-lines examples/output.md5sum priv/output/examples.md5sum
